name: CI - Run Tests

on:
  push:
    branches:
      - main  # Run this workflow when code is pushed to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set up Python 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from the requirements file

      - name: Run tests
        run: |
          pytest  # Run the tests using pytest (you could also use other testing frameworks)
