name: Multiple Jobs on Different Runners

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest  # Job 1 runs on Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run hello.py on Ubuntu
        run: |
          python hello.py

  job2:
    runs-on: windows-latest  # Job 2 runs on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run hello.py on Windows
        run: |
          python hello.py

  job3:
    runs-on: macos-latest  # Job 3 runs on macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run hello.py on macOS
        run: |
          python hello.py
